function [response,p]=histcontour2(fixdur1,fixdur2,xname,yname,filename,onoffopt,bsize,C)
% t = linspace(-1, 1.2, 2000);
% x = (t.^3)+(0.3.*randn(1, 2000));
% y = (t.^6)+(0.3.*randn(1, 2000));
x=fixdur1;
y=fixdur2;
lim1=-.5;
lim2=5;
start1=lim1-bsize-eps(16);
end1=lim2+bsize+eps(16);
trace0 = struct(...
    'x', [lim1 lim2], ...
    'y', [lim1 lim2], ...
    'mode', 'line', ...
    'type','scatter');
trace1 = struct(...
    'x', x, ...
    'y', y, ...
    'mode', 'markers', ...
    'name', 'points', ...
    'marker', struct(...
        'color', 'rgb(102,0,0)', ...
        'size', 3, ...
        'opacity', 0.4), ...
    'type', 'scatter');
trace2 = struct(...
    'x', x, ...
    'y', y, ...
    'name', 'density', ...
    'ncontours', 15, ...
    'colorscale', 'Hot', ...
    'reversescale', true, ...
    'showscale', false, ...
    'type', 'histogram2dcontour');
trace3 = struct(...
    'x', x, ...
    'name', 'x density', ...
    'autobinx', false, ...
    'xbins', struct(...
        'start',start1, ...
        'end', end1, ...
        'size', bsize), ...
    'marker', struct('color', 'rgb(102,0,0)'), ...
        'yaxis', 'y2', ...
        'type', 'histogram');
trace4 = struct(...
    'y', y, ...
    'name', 'y density', ...
    'autobiny', false, ...
    'ybins', struct(...
        'start',start1, ...
        'end', end1, ...
        'size', bsize), ...
    'marker', struct('color', 'rgb(102,0,0)'), ...
        'xaxis', 'x2', ...
        'type', 'histogram');
trace5 = struct(...
    'x', C(1,2:end), ...
    'y', C(2,2:end), ...
    'mode', 'line', ...
    'marker', struct(...
        'color', 'rgb(255,255,255)', ...
        'size', 2, ...
        'opacity', 0.4), ...
    'type','scatter');
data = {trace0,trace1, trace2, trace3, trace4, trace5};
layout = struct(...
    'showlegend', false, ...
    'autosize', false, ...
    'width', 600, ...
    'height', 550, ...
    'xaxis', struct(...
        'domain', [0, 0.85], ...
        'showgrid', false, ...
        'zeroline', false, ...
        'range',[lim1 lim2], ...
        'title',xname), ...
    'yaxis', struct(...
        'domain', [0, 0.85], ...
        'showgrid', false, ...
        'zeroline', false, ...
        'range',[lim1 lim2], ...
        'title',yname), ...
    'margin', struct('t', 50), ...
    'hovermode', 'closest', ...
    'bargap', 0, ...
    'xaxis2', struct(...
        'domain', [0.85, 1], ...
        'showgrid', false, ...
        'zeroline', false), ...
    'yaxis2', struct(...
        'domain', [0.85, 1], ...
        'showgrid', false, ...
        'zeroline', false));
if onoffopt==1
    p.data = data;
    p.layout = layout;
    layout2=struct('layout', layout, 'filename',filename, 'fileopt', 'overwrite');
    response = plotly(data, layout2);
else
    p = plotlyfig; % initalize an empty figure object
    p.data = data;
    p.layout = layout;
    
    p.PlotOptions.FileName = filename;
    
    % Create a standalone HTML file
    response = plotlyoffline(p);
    close()
end
% plot_url = response.url